theme: jekyll-theme-minimal

title: [KEPASA]
description: [Open Source Feed Rss Reader]
#logo: ["https://yt3.ggpht.com/a-/AAuE7mCt6aarYnkBZS4mj2fI-JkdjW1p82oK7EjGMA=s288-mo-c-c0xffffffff-rj-k-no"]
logo: ["http://ak2.imgaft.com/images/new_logo_GDTrans.png"]
show_downloads: ["true"]