theme: jekyll-theme-minimal
title: [KEPASA]
description: [Open Source Feed Rss Reader]
logo: ["https://avatars3.githubusercontent.com/u/14023651?s=400&u=75f6986cbfcabea8db89542eb50f50629361d699&v=4."]
show_downloads: ["true"]