#pusher_app_id: "2954"
#pusher_key: "7381a978f7dd7f9a1117"
#pusher_secret: "abdc3b896a0ffb85d373"

#CAPISTRANO
PRO_WEBAPP_PATH:
WEB_IP_ADDRESS:
WEB_USER:
WEB_SSH_PORT:
DOMAIN: www.kepasa.mx
EMAIL_ADDRESS: reader@kepasa.mx
GMAIL_USERNAME: your_google_email@gmail.com
GMAIL_PASSWORD: your_google_password

SECRET_KEY_BASE: 