# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create({{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create({name: 'Emanuel', city: cities.first)

@giornali = [{rssurl:	"http://www.bbc.co.uk/mundo/ultimas_noticias/index.xml", title: "Ultima Hora – BBC Espanol"},
{rssurl:	"http://www.bbc.co.uk/mundo/temas/internacional/index.xml", title: "Internacional  – BBC Espanol"},
{rssurl:	"http://www.bbc.co.uk/mundo/temas/america_latina/index.xml", title: "America Latina – BBC Espanol"},
{rssurl:	"http://www.bbc.co.uk/mundo/temas/ciencia/index.xml", title: "Ciencia – BBC Espanol"},
{rssurl:	"http://www.bbc.co.uk/mundo/temas/salud/index.xml", title: "Salud – BBC Espanol"},
{rssurl:	"http://www.bbc.co.uk/mundo/temas/tecnologia/index.xml", title: "Tecnologia – BBC Espanol"},
{rssurl:	"http://www.bbc.co.uk/mundo/temas/economia/index.xml", title: "Economia – BBC Espanol"},
{rssurl:	"http://www.bbc.co.uk/mundo/temas/cultura/index.xml", title: "Cultura – BBC Espanol"},
{rssurl:	"http://www.bbc.co.uk/mundo/temas/video/index.xml", title: "Video – BBC Espanol"},
{rssurl:	"http://www.bbc.co.uk/mundo/temas/fotos/index.xml", title: "Fotos – BBC Espanol"},
{rssurl:	"http://cnnespanol.cnn.com/feed/", title: "Mundo – CNN Internacional"},
{rssurl:	"http://feeds2.feedburner.com/cnnmexico/portada", title: "Portada – CNN Mexico"},
{rssurl:	"http://feeds2.feedburner.com/cnnmexico/nacional", title: "Nacional – CNN Mexico"},
{rssurl:	"http://feeds2.feedburner.com/cnnmexico/mundo", title: "Mundo – CNN Mexico"},
{rssurl:	"http://feeds2.feedburner.com/cnnmexico/salud", title: "Vida y Salud – CNN Mexico"},
{rssurl:	"http://feeds2.feedburner.com/cnnmexico/entretenimiento", title: "Entretenimiento – CNN Mexico"},
{rssurl:	"http://feeds2.feedburner.com/cnnmexico/deportes", title: "Deportes – CNN Mexico"},
{rssurl:	"http://feeds2.feedburner.com/cnnexpansion/economia", title: "Economia – CNN Mexico"},
{rssurl:	"http://feeds.feedburner.com/cnnmexico/tecnologia", title: "Tecnologia – CNN Mexico"},
{rssurl:	"http://www.cnnchile.com/rss/", title: "Portada – CNN Chile"},
{rssurl:	"http://actualidad.rt.com/actualidad?rss=1", title: "Actualidad – Russian TV"},
{rssurl:	"http://actualidad.rt.com/economia?rss=1", title: "Economia – Russian TV"},
{rssurl:	"http://actualidad.rt.com/ciencias?rss=1", title: "Ciencia – BBC Espanol"},
{rssurl:	"http://actualidad.rt.com/deporte?rss=1", title: "Deporte – Russian TV"},
{rssurl:	"http://actualidad.rt.com/cultura?rss=1", title: "Cultura – Russian TV"},
{rssurl:	"http://actualidad.rt.com/sociedad?rss=1", title: "Sociedad – Russian TV"},
{rssurl:	"http://actualidad.rt.com/internacional?rss=1", title: "Internacional – Russian TV"},
{rssurl:	"http://actualidad.rt.com/america_latina?rss=1", title: "America Latina – Russian TV"},
{rssurl:	"http://actualidad.rt.com/estados_unidos?rss=1", title: "Estados Unidos – Russian TV"},
{rssurl:	"https://es.noticias.yahoo.com/rss/nacional", title: "Nacional – Yahoo – Espana"},
{rssurl:	"https://es.noticias.yahoo.com/rss/sucesos", title: "Sucesos – Yahoo – Espana"},
{rssurl:	"https://es.noticias.yahoo.com/rss/politica", title: "Politica – Yahoo "},
{rssurl:	"https://es.noticias.yahoo.com/rss/mundo", title: "Mundo – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/europa", title: "Europa – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/america-latina", title: "America Latina – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/estados-unidos", title: "Estados Unidos – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/oriente-proximo", title: "Oriente proximo – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/asia", title: "Asia – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/africa", title: "Africa – Yahoo "},
{rssurl:	"https://es.noticias.yahoo.com/rss/corazon", title: "Corazon – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/perfiles-famosos", title: "Perfiles destacados – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/ciencia", title: "Ciencia – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/salud", title: "Salud – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/espacio", title: "Espacio – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/medio-ambiente", title: "Medio Ambiente – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/sociedad", title: "Sociedad – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/economia", title: "Economia – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/tecnologia", title: "Tecnologia – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/cultura", title: "Cultura – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/deportes", title: "Deportes – Yahoo"},
{rssurl:	"https://es.noticias.yahoo.com/rss/insolitas", title: "Insolitas – Yahoo"},
{rssurl:	"http://clarin.feedsportal.com/c/33088/f/577681/index.rss", title: "Portada – Clarin – Argentina"},
{rssurl:	"http://www.clarin.com/rss/deportes/", title: "Deportes – Clarin – Argentina"},
{rssurl:	"http://contenidos.lanacion.com.ar/herramientas/rss/origen=2", title: "Ultima Hora – La Nacion – Argentina"},
{rssurl:	"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=30", title: "Politica – La Nacion – Argentina"},
{rssurl:	"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=272", title: "Economia – La Nacion – Argentina"},
{rssurl:	"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=131", title: "Deportes- La Nacion – Argentina"},
{rssurl:	"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=120", title: "Espetaculos – La Nacion – Argentina"},
{rssurl:	"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7", title: "Mundo – La Nacion – Argentina"},
{rssurl:	"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=432", title: "Tecnologia – La Nacion – Argentina"},
{rssurl:	"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1312", title: "Moda y Bellezza – La Nacion"},
{rssurl:	"http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1363", title: "Inmuebles Comerciales – La Nacion – Argentina"},
{rssurl:	"http://www.pagina12.com.ar/diario/rss/ultimas_noticias.xml", title: "Ultima Hora – Pagina 12 – Argentina"},
{rssurl:	"http://www.pagina12.com.ar/diario/rss/principal.xml", title: "Edicion Impresa – Pagina 12 – Argentina"},
{rssurl:	"http://www.pagina12.com.ar/diario/rss/espectaculos.xml", title: "Espectaculos – Pagina 12 – Argentina"},
{rssurl:	"http://www.larazon.com.ar/rss/", title: "Portada – La Razon – Argentina"},
{rssurl:	"http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=4", title: "Politica – La Prensa – Argentina"},
{rssurl:	"http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=5", title: "Economia – La Prensa – Argentina"},
{rssurl:	"http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=6", title: "Opinion – La Prensa – Argentina"},
{rssurl:	"http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=7", title: "Mundo – La Prensa – Argentina"},
{rssurl:	"http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=8", title: "Actualidad – La Prensa – Argentina"},
{rssurl:	"http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=9", title: "Deportes – La Prensa – Argentina"},
{rssurl:	"http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=10", title: "Espetaculos – La Prensa – Argentina"},
{rssurl:	"http://www.la-razon.com/rss/mundo/", title: "Mundo – La Razon – Bolivia"},
{rssurl:	"http://www.la-razon.com/rss/sociedad/Ciencia_tecnologia/", title: "Ciencia y Tecnologia – La Razon – Bolivia"},
{rssurl:	"http://www.la-razon.com/rss/nacional/", title: "Nacional – La Razon – Bolivia"},
{rssurl:	"http://www.la-razon.com/rss/la_revista/espectaculos/", title: "Espectaculos – La Razon – Bolivia"},
{rssurl:	"http://www.lostiempos.com/rss/lostiempos-titulares.xml", title: "Portada – Los Tiempos – Bolivia"},
{rssurl:	"http://www.lostiempos.com/rss/lostiempos-ultimas.xml", title: "Las Ultima Hora – Los Tiempos – Bolivia"},
{rssurl:	"http://www.lostiempos.com/rss/lostiempos-deportes.xml", title: "Deportes – Los Tiempos – Bolivia"},
{rssurl:	"http://www.lostiempos.com/rss/lostiempos-economia.xml", title: "Economia – Los Tiempos – Bolivia"},
{rssurl:	"http://www.eldeber.com.bo/rss/", title: "Portada – El Deber – Bolivia"},
{rssurl:	"http://www.lacuarta.com/app/feed?type=rss&sc=TEFDVUFSVEE=", title: "Portada – La Cuarta: El diario Popular – Chile"},
{rssurl:	"http://cl.elmostrador.feedsportal.com/c/33501/f/584528/index.rss", title: "Todas Las Noticias – El Mostrador – Chile"},
{rssurl:	"http://www.elmostrador.cl/destacado/feed/", title: "Destacados – El Mostrador – Chile"},
{rssurl:	"http://www.elmostrador.cl/dia/feed/", title: "El Dia – El Mostrador – Chile"},
{rssurl:	"http://www.elmostrador.cl/noticias/pais/feed/", title: "Pais – El Mostrador – Chile"},
{rssurl:	"http://www.elmostrador.cl/noticias/mundo/feed/", title: "Mundo – El Mostrador – Chile"},
{rssurl:	"http://www.elmostrador.cl/noticias/negocios/feed/", title: "Negozios – El Mostrador – Chile"},
{rssurl:	"http://www.elmostrador.cl/noticias/cultura/feed/", title: "Cultura – El Mostrador - Chile "},
{rssurl:	"http://www.elmostrador.cl/vida-en-linea/feed/", title: "Vida En Linea – El Mostrador – Chile"},
{rssurl:	"http://www.elmostrador.cl/opinion/feed/", title: "Opinion y Blogs – El Mostrador – Chile"},
{rssurl:	"http://www.elmostrador.cl/kiosko/feed/", title: "Kiosko"},
{rssurl:	"http://www.lahora.cl/feed/manager?type=rss&sc=TEFIT1JB&notAllowed=47-48-51-54-53-52-50-49", title: "Portada – La Hora – Chile"},
{rssurl:	"http://www.estrategia.cl/noticias.xml", title: "Negocios – Estrategia – Chile"},
{rssurl:	"https://www.df.cl/noticias/site/list/port/rss.xml", title: "Negocios – Diario Financiero – Chile"},
{rssurl:	"http://www.pulso.cl/feed/manager?type=rss&sc=UFVMU08=", title: "Negocios – Pulso – Chile"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607844/index.rss", title: "Ultima Hora – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607845/index.rss", title: "Politica – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607853/index.rss", title: "Mundo – El Espectador – Colombia"},
{rssurl:	"http://www.elespectador.com/cultura/feed", title: "Cultura – El Espectador - Colombia "},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607848/index.rss", title: "Economia – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607872/index.rss", title: "Tecnologia – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607850/index.rss", title: "Investigacion – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607852/index.rss", title: "Salud – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607851/index.rss", title: "Educacion – El Espectador – Colombia"},
{rssurl:	"http://www.elespectador.com/noticias/medio-ambiente/feed", title: "Medio Ambiente – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607856/index.rss", title: "Actualidad – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607859/index.rss", title: "Deportes – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607866/index.rss", title: "Futbol Colombiano – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607867/index.rss", title: "Futbol Internacional – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607861/index.rss", title: "Automovilismo – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607864/index.rss", title: "Ciclismo – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607871/index.rss", title: "Tenis – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607862/index.rss", title: "Baloncesto – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607863/index.rss", title: "Beisbol – El Espectador – Colombia"},
{rssurl:	"http://www.elespectador.com/deportes/golf/feed", title: "Golf – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607873/index.rss", title: "Autos VIP – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607874/index.rss", title: "Buen Viaje VIP – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607875/index.rss", title: "Ellas – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607876/index.rss", title: "Bebe – El Espectador – Colombia"},
{rssurl:	"http://feeds.elespectador.com/c/33813/f/607877/index.rss", title: "Gastronomia – El Espectador – Colombia"},
{rssurl:	"http://www.nacion.com/rss/", title: "Portada – La Nacion – Costa Rica"},
{rssurl:	"http://www.nacion.com/rss/latest/?contentType=NWS", title: "Ultima Hora – La Nacion – Costa Rica"},
{rssurl:	"http://www.nacion.com/rss/nacional/", title: "Nacional – La Nacion – Costa Rica"},
{rssurl:	"http://www.nacion.com/rss/ocio/", title: "Ocio – La Nacion – Costa Rica"},
{rssurl:	"http://www.nacion.com/rss/sucesos/", title: "Sucesos – La Nacion – Costa Rica"},
{rssurl:	"http://www.nacion.com/rss/deportes/", title: "Deportes – La Nacion – Costa Rica"},
{rssurl:	"http://www.nacion.com/rss/mundo/", title: "Mundo – La Nacion – Costa Rica"},
{rssurl:	"http://www.nacion.com/rss/economia/", title: "Economia – La Nacion – Costa Rica"},
{rssurl:	"http://www.nacion.com/rss/vivir/", title: "Vivir – La Nacion – Costa Rica"},
{rssurl:	"http://www.nacion.com/rss/tecnologia/", title: "Tecnologia – La Nacion – Costa Rica"},
{rssurl:	"http://www.nacion.com/rss/opinion/", title: "Opinion – La Nacion – Costa Rica"},
{rssurl:	"http://feeds.feedburner.com/eltiempoec", title: "Portada – El Tiempo – Ecuador"},
{rssurl:	"http://www.elcomercio.com/rss/actualidad", title: "Actualidad – El Comercio – Ecuador"},
{rssurl:	"http://www.elcomercio.com/rss/tendencias", title: "Tendencias – El Comercio – Ecuador"},
{rssurl:	"http://elcomercio.com/rss/deportes", title: "Deportes – El Comercio – Ecuador"},
{rssurl:	"http://www.elcomercio.com/rss/opinion", title: "Opinion – El Comercio – Ecuador"},
{rssurl:	"http://www.lahora.com.ec/rss/rss.php?seccion=pais", title: "Noticias Ecuador – La Hora – Ecuador"},
{rssurl:	"http://www.lahora.com.ec/rss/rss.php?seccion=ultimahora", title: "Ultima Hora – La Hora – Ecuador"},
{rssurl:	"http://www.lahora.com.ec/rss/rss.php?seccion=mundo", title: "Mundo – La Hora – Ecuador"},
{rssurl:	"http://www.lahora.com.ec/rss/rss.php?seccion=economia", title: "Economia – La Hora – Ecuador"},
{rssurl:	"http://www.lahora.com.ec/rss/rss.php?seccion=deportes", title: "Deportes – La Hora – Ecuador"},
{rssurl:	"http://www.lahora.com.ec/rss/rss.php?seccion=opinion", title: "Opinion – La Hora – Ecuador"},
{rssurl:	"http://www.lahora.com.ec/rss/rss.php?seccion=farandula", title: "Farandula – La Hora – Ecuador"},
{rssurl:	"http://www.lahora.com.ec/rss/rss.php?seccion=cultura", title: "Cultura – La Hora – Ecuador"},
{rssurl:	"http://www.lahora.com.ec/rss/rss.php?seccion=social", title: "Social – La Hora – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/migrantes.xml", title: "Migrantes – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/politica.xml", title: "Politica – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/economia.xml", title: "Economia – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/seguridad", title: "Seguridad – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/caricaturas", title: "Caricaturas – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/deportes.xml", title: "Deportes – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/futbol.xml", title: "Futbol – EL Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/campeonato", title: "Campeonato – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/tenis.xml", title: "Tenis – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/intercultural", title: "Intercultural – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/tendencias.xml", title: "Tendencias – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/tecnologia.xml", title: "Tecnologia – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/cultura.xml", title: "Cultura – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/ecologia.xml", title: "Ecologia – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/cine-y-tv.xml", title: "Cine y TV – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/musica.xml", title: "Musica – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/salud.xml", title: "Salud – El Universo – Ecuador"},
{rssurl:	"http://www.eluniverso.com/rss/gente.xml", title: "Gente – El Universo – Ecuador"},
{rssurl:	"http://www.telegrafo.com.ec/index.php?option=com_zoo&task=feed&app_id=6&category_id=0&format=feed&type=rss&Itemid=153", title: "Actualidad – Telegrafo – Ecuador"},
{rssurl:	"http://www.telegrafo.com.ec/index.php?option=com_zoo&task=feed&app_id=2&category_id=0&format=feed&type=rss&Itemid=262", title: "Deportes – Telegrafo – Ecuador"},
{rssurl:	"http://www.telegrafo.com.ec/index.php?option=com_zoo&task=feed&app_id=1&category_id=0&format=feed&type=atom&Itemid=156", title: "Economia – Telegrafo – Ecuador"},
{rssurl:	"http://www.telegrafo.com.ec/index.php?option=com_zoo&task=feed&app_id=8&category_id=0&format=feed&type=rss&Itemid=278", title: "Cultura – Telegrafo – Ecuador"},
{rssurl:	"http://www.telegrafo.com.ec/index.php?option=com_zoo&task=feed&app_id=3&category_id=0&format=feed&type=rss&Itemid=161", title: "Opiniones – Telegrafo – Ecuador"},
{rssurl:	"http://www.telegrafo.com.ec/index.php?option=com_zoo&task=feed&app_id=7&category_id=0&format=feed&type=rss&Itemid=162", title: "Sociedad – Telegrafo – Ecuador"},
{rssurl:	"http://www.telegrafo.com.ec/index.php?option=com_zoo&task=feed&app_id=15&category_id=0&format=feed&type=rss&Itemid=163", title: "Tecnologia – Telegrafo – Ecuador"},
{rssurl:	"http://www.telegrafo.com.ec/index.php?option=com_zoo&task=feed&app_id=14&category_id=0&format=feed&type=rss&Itemid=155", title: "Mundo – Telegrafo – Ecuador"},
{rssurl:	"http://www.telegrafo.com.ec/index.php?option=com_zoo&task=feed&app_id=4&category_id=0&format=feed&type=rss&Itemid=123", title: "Multimedia – Telegrafo – Ecuador"},
{rssurl:	"http://www.reforma.com/rss/portada.xml", title: "Portada – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/negocios.xml", title: "Negocios – Negocios – Mexico"},
{rssurl:	"http://www.reforma.com/rss/cultura%20.xml", title: "Cultura – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/gadgets.xml", title: "Gadgets – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/buena%20mesa.xml", title: "Buena Mesa – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/universitarios.xml", title: "Universitartios – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/ciudad.xml", title: "Ciudad – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/internacional.xml", title: "Internacional – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/ciencia.xml", title: "Ciencia – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/automotriz.xml", title: "Automotriz – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/verde.xml", title: "Verde – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/primera%20fila.xml", title: "Primera Fila – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/justicia.xml", title: "Justicia – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/cancha.xml", title: "Cancha – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/nacional.xml", title: "Nacional – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/de%20viaje.xml", title: "De Viaje – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/entremuros.xml", title: "Entremuros – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/estados.xml", title: "Estados – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/gente.xml", title: "Gente – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/editoriales.xml", title: "Opiniones – Reforma – Mexico"},
{rssurl:	"http://www.reforma.com/rss/moda.xml", title: "Moda – Reforma – Mexico"},
{rssurl:	"http://www.elnorte.com/rss/portada.xml", title: "Portada – El Norte – Mexico"},
{rssurl:	"http://www.eluniversal.com.mx/rss/", title: "Portada – El Universal – Mexico"},
{rssurl:	"http://www.frontera.info/rss/rss.xml", title: "Portada – Frontera – Mexico – Baja California"},
{rssurl:	"http://www.frontera.info/rss/rsspoliciaca.xml", title: "Policiaca – La Cronica – Mexico – Baja California"},
{rssurl:	"http://www.frontera.info/rss/rsslocal.xml", title: "Local – Frontera – Mexico – Baja California"},
{rssurl:	"http://www.frontera.info/rss/rsssandiego.xml", title: "San Diego – Frontera – Mexico - Baja California"},
{rssurl:	"http://www.frontera.info/rss/rssnacional.xml", title: "Nacional – Frontera – Mexico – Baja California"},
{rssurl:	"http://www.frontera.info/rss/rssinternacional.xml", title: "Internacional – Frontera – Mexico - Baja California"},
{rssurl:	"http://www.frontera.info/rss/rssdeportes.xml", title: "Deportes – Frontera – Mexico - Baja California"},
{rssurl:	"http://www.frontera.info/rss/rssEntretenimiento.xml", title: "Entretenimiento – Frontera – Mexico - Baja California"},
{rssurl:	"http://www.frontera.info/rss/rsscienciaytecnologia.xml", title: "Ciencia y Tecnología – Frontera – Mexico - Baja California"},
{rssurl:	"http://www.frontera.info/rss/rssvidayestilo.xml", title: "Vida y Estilo – Frontera – Mexico - Baja California"},
{rssurl:	"http://www.el-mexicano.com.mx/rss/ultimasnoticiasrss.xml", title: "Portada – El Mexicano – Mexico - Baja California"},
{rssurl:	"http://www.lacronica.com/rss/rss.xml", title: "Portada – La Cronica – Mexico - Baja California"},
{rssurl:	"http://www.lacronica.com/rss/rsspoliciaca.xml", title: "Policiaca – La Cronica – Mexico – Baja California"},
{rssurl:	"http://www.lacronica.com/rss/rsslocal.xml", title: "Local  – La Cronica – Mexico – Baja California"},
{rssurl:	"http://www.lacronica.com/rss/rssnacional.xml", title: "Nacional  – La Cronica – Mexico – Baja California"},
{rssurl:	"http://www.lacronica.com/rss/rssinternacional.xml", title: "Internacional  – La Cronica – Mexico – Baja California"},
{rssurl:	"http://www.lacronica.com/rss/rssdeportes.xml", title: "Deportes  – La Cronica – Mexico – Baja California"},
{rssurl:	"http://www.lacronica.com/rss/rssEntretenimiento.xml", title: "Entretenimiento  – La Cronica – Mexico – Baja California"},
{rssurl:	"http://www.lacronica.com/rss/rsscienciaytecnologia.xml", title: "Ciencia y Tecnología  – La Cronica – Mexico – Baja California"},
{rssurl:	"http://www.lacronica.com/rss/rssvidayestilo.xml", title: "Vida y Estilo  – La Cronica – Mexico – Baja California"}]

@giornali.each do |t|
  #Newspaper.create(rssurl: t[:rssurl], title: t[:title])
  #if New.update_from_feed(t[:rssurl]).blank?
    
  #  puts "ok"
  
  #else
    
  #  puts t[:rssurl]
  
  #end
  
  #sleep 5
  
  Newspaper.create(rssurl: t[:rssurl], title: t[:title])
  
  begin
    
  New.update_from_feed(t[:rssurl]).blank?
  
  rescue Exception
  
  puts "Qualcosa e' andato storto!"
  
  end
  
end